=== manuelrojorabadan02-design/LENGUAJE-DE-MARCA/viejo/simulacro examen/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="departamento" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="empleado" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="edad" type="xs:positiveInteger"/>
                    <xs:element name="email" type="xs:string"/>
                    <xs:element name="salario">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:decimal">
                            <xs:attribute name="moneda" type="xs:string" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                  <xs:attribute name="tipo">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="fijo"/>
                        <xs:enumeration value="temporal"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
      <xs:attribute name="pais" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== manuelrojorabadan02-design/LENGUAJE-DE-MARCA/viejo/simulacro examen/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE empresa SYSTEM "ejercicio1.xsd">
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema"
  xsi:noNamespaceSchemaLocation="ejercicio1.xsd">

<empresa nombre="TechNova" pais="España"></empresa>
  <departamento id="D01">
    <nombre>Desarrollo</nombre>
    <empleado id="E100" tipo="fijo">
      <nombre>Lucía Martínez</nombre>
      <edad>29</edad>
      <email>lucia.martinez@technova.es</email>
      <salario moneda="EUR">28000</salario>
    </empleado>
    <empleado id="E101" tipo="temporal">
      <nombre>Javier Ramos</nombre>
      <edad>22</edad>
      <email>javier.ramos@technova.es</email>
      <salario moneda="EUR">18000</salario>
    </empleado>
  </departamento>
  <departamento id="D02">
    <nombre>Marketing</nombre>
    <empleado id="E200" tipo="fijo">
      <nombre>Ana Torres</nombre>
      <edad>34</edad>
      <email>ana.torres@technova.es</email>
      <salario moneda="EUR">32000</salario>
    </empleado>
  </departamento>
</empresa>
